### ISSUE TITLE
`npm test`実行時に"Jest encountered an unexpected toke"エラー

### ISSUE THREAD

**Issue by MaximizedOwl** [MaximizedOwl/simple-markdown-editor-ts#2]
# エラー内容
下記のエラーメッセージが出る。
```
 FAIL  src/App.test.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /foobuzz/Documents/Sandbox/simple-markdown-editor-ts/node_modules/react-markdown/index.js:6
    export {uriTransformer} from './lib/uri-transformer.js'
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      1 | import { useState } from 'react';
    > 2 | import ReactMarkdown from 'react-markdown';
        | ^
      3 | import remarkGfm from 'remark-gfm';
      4 | import './App.css';
      5 |

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/App.tsx:2:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        3.498 s
Ran all test suites related to changed files.

Watch Usage
 › Press a to run all tests.
 › Press f to run only failed tests.
 › Press q to quit watch mode.
 › Press p to filter by a filename regex pattern.
 › Press t to filter by a test name regex pattern.
 › Press Enter to trigger a test run.

```

# 考察
node_modules の中で`SyntaxError: Unexpected token 'export'`と言われる。

**Comment by MaximizedOwl** [comment]
# 解決策

```
"test": "react-scripts test --transformIgnorePatterns \"node_modules/(?!your-module-name)/\"",
```

# 参考にした文献
1. https://github.com/facebook/create-react-app/issues/2537#issuecomment-390341713
